CREATE TABLE delegation_month_end_states (month_start DATE NOT NULL, resolver TEXT NOT NULL, delegator TEXT NOT NULL, delegated_amount NUMERIC(78,0) NOT NULL CHECK (delegated_amount > 0), PRIMARY KEY (month_start,resolver,delegator));
CREATE TABLE delegation_snapshot_checkpoints (month_start DATE PRIMARY KEY, completed_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE resolver_monthly_reward_rates (month_start DATE NOT NULL, resolver_address TEXT NOT NULL, distributor_address TEXT NOT NULL, reward_token_address TEXT NOT NULL, reward_rate NUMERIC NOT NULL CHECK (reward_rate >= 0), rewards_updater TEXT NOT NULL DEFAULT '', PRIMARY KEY (month_start,resolver_address));
CREATE TABLE delegation_monthly (
 month_start DATE NOT NULL, month_end DATE NOT NULL CHECK (month_end=(month_start+INTERVAL '1 month')::DATE), resolver_address TEXT NOT NULL, distributor_address TEXT, delegator_address TEXT NOT NULL, reward_rate NUMERIC CHECK (reward_rate>0), delegation_weight NUMERIC NOT NULL CHECK (delegation_weight>0), reward_amount NUMERIC CHECK (reward_amount>0), resolver_total_reward NUMERIC CHECK (resolver_total_reward>0), epoch_id NUMERIC CHECK (epoch_id>0), merkle_root TEXT CHECK (merkle_root ~ '^0x[0-9a-f]{64}$'), merkle_proof TEXT[], indexed_block_number BIGINT NOT NULL DEFAULT 0, calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(month_start,resolver_address,delegator_address)
) PARTITION BY RANGE(month_start);
CREATE INDEX delegation_monthly_resolver_month_idx ON delegation_monthly(resolver_address,month_start);
CREATE TABLE monthly_root_submissions (
 month_start DATE NOT NULL, resolver_address TEXT NOT NULL, distributor_address TEXT NOT NULL, reward_token_address TEXT NOT NULL, rewards_updater TEXT NOT NULL DEFAULT '', reward_rate NUMERIC NOT NULL CHECK(reward_rate>0), total_reward NUMERIC NOT NULL CHECK(total_reward>0), epoch_id NUMERIC NOT NULL CHECK(epoch_id>0), merkle_root TEXT NOT NULL CHECK(merkle_root ~ '^0x[0-9a-f]{64}$'), root_submission_tx_hash TEXT, root_submission_nonce BIGINT, root_submission_gas_limit BIGINT, root_submission_gas_tip_cap NUMERIC, root_submission_gas_fee_cap NUMERIC, root_submission_attempts INTEGER NOT NULL DEFAULT 0 CHECK(root_submission_attempts>=0), max_attempts INTEGER NOT NULL DEFAULT 8 CHECK(max_attempts>0), next_retry_at TIMESTAMPTZ, root_submission_status TEXT NOT NULL DEFAULT 'not_submitted' CHECK(root_submission_status IN ('not_submitted','processing','submitted','confirmed','failed','failed_permanent')), root_submission_submitted_at TIMESTAMPTZ, root_submission_confirmed_at TIMESTAMPTZ, root_submission_error TEXT, indexed_block_number BIGINT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(month_start,resolver_address)
);
CREATE INDEX monthly_root_submissions_status_idx ON monthly_root_submissions(root_submission_status,month_start);
CREATE INDEX monthly_root_submissions_retry_idx ON monthly_root_submissions(root_submission_status,next_retry_at);
CREATE TABLE monthly_workflows (month_start DATE PRIMARY KEY, status TEXT NOT NULL DEFAULT 'settlement_pending' CHECK(status IN ('settlement_pending','settlement_processing','settled','merkle_pending','merkle_processing','root_pending','root_processing','confirmed','failed','failed_permanent')), attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts>=0), last_error TEXT, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX monthly_workflows_status_idx ON monthly_workflows(status,month_start);
